### ISSUE TITLE
resolve path incorrectly in terminal mode

### ISSUE THREAD

**Issue by zhaoyao91** [gajus/require-new#2]
I didn't try it in code, but I tried it in node terminal.

requireNew('./test') lead to the error:

```
  Error: Cannot find module '././test'
      at Function.Module._resolveFilename (module.js:336:15)
      at Function.require.resolve (module.js:388:19)
      at requireNew (/Users/zhaoyao-code/workspace/ydcy/pj-b/server/node_modules/require-new/src/require-new.js:21:26)
      at repl:1:1
      at REPLServer.defaultEval (repl.js:132:27)
      at bound (domain.js:254:14)
      at REPLServer.runBound [as eval] (domain.js:267:12)
      at REPLServer.<anonymous> (repl.js:279:12)
      at REPLServer.emit (events.js:107:17)
      at REPLServer.Interface._onLine (readline.js:214:10)
```

**Comment by gajus** [comment]
For documentation purposes:

```
curiosity:require-new gajus$ echo "require('./src')('./src')" | node

module.js:338
    throw err;
          ^
Error: Cannot find module '././src'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.require.resolve (module.js:388:19)
    at module.exports (/Users/gajus/Documents/dev/gajus/require-new/src/index.js:26:26)
    at [stdin]:1:17
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:430:26)
    at node.js:567:27
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

In the above case:

```
stackTrace.get()[1].getFileName() [stdin]
```

and

```
curiosity:require-new gajus$ node -e "require('./src')('./src')"

module.js:338
    throw err;
          ^
Error: Cannot find module '././src'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.require.resolve (module.js:388:19)
    at module.exports (/Users/gajus/Documents/dev/gajus/require-new/src/index.js:26:26)
    at [eval]:1:17
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:430:26)
    at node.js:567:27
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

is:

```
stackTrace.get()[1].getFileName() [eval]
```

**Comment by gajus** [comment]
With this in mind, I have updated the code to use `process.cwd()` whenever "stdin" or "eval" is the stack origin.

**Comment by gajus** [comment]
@4368baed3c199c8284103a8842896d1d717e6720
